### ISSUE TITLE
where is the core code of the BCP？

### ISSUE THREAD

**Issue by yang654123** [DeepMed-Lab-ECNU/BCP#11]
你好作者，我想咨询一下关于将标记数据集copy到未标记数据的背景的中去，你在代码中是如何做的

**Comment by byhwhite** [comment]
你好，我们在这里完成图像间的copy-paste：
https://github.com/DeepMed-Lab-ECNU/BCP/blob/b62b10b4a23b1e73b596850806677637538bf9ee/code/ACDC_BCP_train.py#L372-L373
注意我们在文中所提到的foreground和background并非严格意义上的“仅包含前景”和“仅包含背景”，我们的目的是简要的称呼索要copy的patch和所paste到的目标图像，若给您带来困扰我们表示歉意！

**Comment by yang654123** [comment]
谢谢您的回复，我还有个一个问题就是，您在实验中是如何实现将GT粘贴到生成的伪标签上去的

**Comment by byhwhite** [comment]
> 谢谢您的回复，我还有个一个问题就是，您在实验中是如何实现将GT粘贴到生成的伪标签上去的

不客气。我们使用`mixloss`函数来实现相对应的伪标签和GT计算：
https://github.com/DeepMed-Lab-ECNU/BCP/blob/b62b10b4a23b1e73b596850806677637538bf9ee/code/ACDC_BCP_train.py#L167-L179
在这个函数中，我们将预测分别和GT与伪标签进行loss计算，并使用weight map以使得只有对应区域的loss被相加。

**Comment by yang654123** [comment]
十分感谢您的回复！
