### ISSUE TITLE
细节问题

### ISSUE THREAD

**Issue by JianJianYin** [DeepMed-Lab-ECNU/BCP#14]
您好，感谢您卓越的工作，我仔细阅读了您的代码，我对ACDC_BCP_train.py文件中的 第89行 get_ACDC_2DLargestCC 方法的作用不太清楚，您能给我解答一下嘛。非常感谢

**Comment by byhwhite** [comment]
您好，该函数作用是选取mask中每一类的最大连通分量，以对pseudo label进行后处理减少噪声。
