### ISSUE TITLE
Pretrain model

### ISSUE THREAD

**Issue by shenbw99** [DeepMed-Lab-ECNU/BCP#15]
Dear Sir, thank you for your great work.
We want to follow the semi-supervised segmentation work, and test on LA Heart and ACDC dataset. The split of the train dataset and validation dataset will follow your work.
We want to visualize and compare with previous SOTA  methods. I would greatly appreciate it if you could provide pre-trained models for previous methods like DTC, UAMT, SASSNet on LA and ACDC.

**Comment by byhwhite** [comment]
Hi! Pretrained models can be found at thier github: [DTC](https://github.com/HiLab-git/DTC), [UA-MT](https://github.com/yulequan/UA-MT), [SASSNet](https://github.com/kleinzcy/SASSnet). Hope these could be help!
