### ISSUE TITLE
关于测试集

### ISSUE THREAD

**Issue by aixiaobaikkk** [DeepMed-Lab-ECNU/BCP#19]
你好，我注意到在pre train的时候用的测试集来保留最好的结果，然后self train时再加载测试集上最好的结果，这样是不是有些不妥之处，因为最近我也在关注这方面的工作，对于这种双阶段的训练，是不是最好再划分个验证集

**Comment by byhwhite** [comment]
您好！感谢您对我们工作的关注。非常好的问题！在训练时为了和previous work公平比较，我们没有对setting进行任何改变，包括训练集、验证集和测试集的划分。在前人的工作中，LA和Pancreas并非没有划分出验证集，model也是保留在测试集上的最佳结果。ACDC上划分出了验证集，这点我们也与前人保持了一致。我们在实验初期也对这种方式保留了疑问，但是如果划分出验证集则意味着训练集和测试集的变动，不方便与经典工作进行公平比较。若您有具体可实施方案还请提出宝贵意见，我们在接下来的研究中会参考，感谢！

**Comment by aixiaobaikkk** [comment]
非常感谢您的回复！我在复现您的工作时都获得了不错的结果，只是在3个标签数据的ACDC数据数据上并没有达到论文中的效果，大约差了3%左右，更有趣的是，在验证集上的结果大概在88%，而在测试集只有83%，在7个标签数据下的验证集和测试集的差距在1以内，我对以上结果很困惑，是模型过拟合了吗？为啥差距表现这么大，还是说在少标签下预训练的轮次应该降低一些，期待您的解答

**Comment by byhwhite** [comment]
> 非常感谢您的回复！我在复现您的工作时都获得了不错的结果，只是在3个标签数据的ACDC数据数据上并没有达到论文中的效果，大约差了3%左右，更有趣的是，在验证集上的结果大概在88%，而在测试集只有83%，在7个标签数据下的验证集和测试集的差距在1以内，我对以上结果很困惑，是模型过拟合了吗？为啥差距表现这么大，还是说在少标签下预训练的轮次应该降低一些，期待您的解答

您好，关于代码复现，我们在复现他人工作时也会有类似情况出现。您的torch、python和cuda版本是否与我们一致？我们在不同labeled ratio情况下是没有改变预训练轮次等参数的，只改变labeled ratio。

**Comment by aixiaobaikkk** [comment]
感谢您的回复，我主要困惑点是验证集和测试集相差太大，验证的性能表现是ok的，可是测试就低了不少

**Comment by byhwhite** [comment]
> 感谢您的回复，我主要困惑点是验证集和测试集相差太大，验证的性能表现是ok的，可是测试就低了不少

我认为大概率是因为保存的checkpoint的确是偏向验证集的，您可以尝试更改保存checkpoint的条件：比如loss最低时或最后一个epoch时等。

**Comment by aixiaobaikkk** [comment]
> > 感谢您的回复，我主要困惑点是验证集和测试集相差太大，验证的性能表现是ok的，可是测试就低了不少
> 
> 我认为大概率是因为保存的checkpoint的确是偏向验证集的，您可以尝试更改保存checkpoint的条件：比如loss最低时或最后一个epoch时等。

感谢您的解答，我去尝试一下
