### ISSUE TITLE
关于损失loss

### ISSUE THREAD

**Issue by CamillerFerros** [DeepMed-Lab-ECNU/BCP#20]
你好，我正在复现了你的工作，结果很好，但是我有一个疑问。[21:06:27.134] iteration 16950: loss: 0.597458, mix_dice: 1.172820, mix_ce: 0.022097这是我的训练过程中的损失，为什么ce_loss能够降下去但是dice_loss与初始比不怎么下降呢。我复现其他工作对于ACDC数据集用的dice_loss也能下降的和ce_loss一样，为什么这篇工作的dice_loss无法下降呢。

**Comment by byhwhite** [comment]
你好，我们在代码中使用了tensorboard来记录loss情况，您方便贴一下loss、mix_dice、mix_ce三个loss的可视化图像吗？

**Comment by CamillerFerros** [comment]
![image](https://github.com/DeepMed-Lab-ECNU/BCP/assets/117154638/3b6faa78-8028-4e31-8d2f-ddb147377ee1)
您好，这是我训练的loss

**Comment by CamillerFerros** [comment]
我参考别的工作中acdc数据集的dice_loss和ce_loss，他们的dice_loss也能和ce_loss降到0.05以下，但是您工作中的dice_loss并不能降低。

**Comment by byhwhite** [comment]
谢谢您，很有趣的现象！从您的图中可以看到dice_loss也是逐渐降低的，只是降低的幅度没有那么多。出现这种现象的原因我猜测是因为我们的dice loss与原dice loss不同：因为图像包含相同和不相同语义的部分，我们在计算dice loss时给参与计算的两张图像乘上了weight map来保证参与计算的部分是相同语义的分割结果，不相同部分为0。很抱歉我们在这个方面没有像您一样细致入微的观察，在后续工作中我们会特别关注到这一部分。再次感谢您的宝贵问题！
