### ISSUE TITLE
關於ACDC資料集訓練

### ISSUE THREAD

**Issue by wenshan1212** [DeepMed-Lab-ECNU/BCP#23]
您好，在reproduce這邊論文時，對於訓練ACDC資料集的結果都沒有辦法有固定的訓練數值（訓練一次出來的數值，和第二次訓練出來的數值不同）？想請問是什麼原因？謝謝

**Comment by byhwhite** [comment]
> 您好，在reproduce這邊論文時，對於訓練ACDC資料集的結果都沒有辦法有固定的訓練數值（訓練一次出來的數值，和第二次訓練出來的數值不同）？想請問是什麼原因？謝謝

您好，不知道您有没有跑过 SSNet？我们的 deterministic 设置与 SSNet 相同。
