### ISSUE TITLE
acdc数据集

### ISSUE THREAD

**Issue by CamillerFerros** [DeepMed-Lab-ECNU/BCP#26]
您好，当我在您的代码当中删掉了bcp模块，不进行bcp混合操作，直接用unet对acdc中的7个有标签和63个无标签进行训练，结果一样能跑到88.8，您能解释一下吗，不知是否是我的代码有问题，我只是修改了混合的部分不进行混合。

**Comment by CamillerFerros** [comment]
![Uploading 2023-06-02 12-09-48 的屏幕截图.png…]()

**Comment by CamillerFerros** [comment]
![Uploading 2023-06-02 12-09-48 的屏幕截图.png…]()

**Comment by CamillerFerros** [comment]
![2023-06-02 12-09-48 的屏幕截图](https://github.com/DeepMed-Lab-ECNU/BCP/assets/117154638/c07b5456-7744-4f93-a5e7-1c12fe7f2109)

**Comment by CamillerFerros** [comment]
![2023-11-21_14-57](https://github.com/DeepMed-Lab-ECNU/BCP/assets/117154638/c7b262bd-8988-4bc4-84f9-e85f884424a4)

**Comment by byhwhite** [comment]
> 您好，当我在您的代码当中删掉了bcp模块，不进行bcp混合操作，直接用unet对acdc中的7个有标签和63个无标签进行训练，结果一样能跑到88.8，您能解释一下吗，不知是否是我的代码有问题，我只是修改了混合的部分不进行混合。

您好，感谢您对我们工作关注。我们看到您的问题后也进行了您的实验，在7个有标签数据上也达到了与BCP几乎相同的性能，但是在3个有标签数据上只有75.8.我们推测出现这样结果的原因是我们的框架除去混合部分后，7个有标签数据已经足够使得网络充分训练；数据量较少时，BCP混合的帮助才会更加凸显。
