### ISSUE TITLE
关于数据量

### ISSUE THREAD

**Issue by 7tu** [DeepMed-Lab-ECNU/BCP#27]
您好作者，首先感谢您出色的工作！想请教您一些关于数据量的问题。例如在LA数据集，labelnum=8的情况下。我看您在论文中提到只使用了带标记的数据来训练teacher net，在代码实现pre_train的过程中好像也用到了未标记的数据。想请问您teacher net的训练具体是用了什么样的数据呢

**Comment by byhwhite** [comment]
> 您好作者，首先感谢您出色的工作！想请教您一些关于数据量的问题。例如在LA数据集，labelnum=8的情况下。我看您在论文中提到只使用了带标记的数据来训练teacher net，在代码实现pre_train的过程中好像也用到了未标记的数据。想请问您teacher net的训练具体是用了什么样的数据呢

您好，感谢您对我们工作的关注。预训练teacher network时只使用了有标记数据：我们在取image和label时只取了volume batch的前args.labeled_bs个数据，这些都是有标记数据，在此基础上我们又用sub_bs来对有标记数据分成两部分，以此进行cutmix的预训练(这部分在论文中有介绍)。

**Comment by 7tu** [comment]
感谢，所以说在LA数据集，labelnum=8的情况下，预训练中只使用了8个有标记的数据进行反复训练来作为teacher net，其中使用到了您提到的数据增强方法？

**Comment by byhwhite** [comment]
> 感谢，所以说在LA数据集，labelnum=8的情况下，预训练中只使用了8个有标记的数据进行反复训练来作为teacher net，其中使用到了您提到的数据增强方法？

是的

**Comment by 7tu** [comment]
非常感谢您~
