### ISSUE TITLE
关于新数据切割

### ISSUE THREAD

**Issue by indifferenttan** [DeepMed-Lab-ECNU/BCP#28]
您好，我使用您的代码跑自己数据集的时候发现无法在代码中找到生成data_split文件夹下ACDC文件夹中的五个list文件，请问您是怎么生成这五个文件的。
![image](https://github.com/DeepMed-Lab-ECNU/BCP/assets/49123251/ecdab084-7320-428b-9b54-93cabb46db36)
还有就是在运行acdc_data_processing.py时在BCP-main/ACDC/data中生成的.h5文件只有标签的切片，原始图像在训练中不需要切片吗还是我需要另行切割？
抱歉，问题比较多，请见谅！

**Comment by byhwhite** [comment]
[关于ACDC的list文件以及预处理过的图像和标签都可以在[这里](https://github.com/HiLab-git/SSL4MIS/tree/master/data/ACDC)获取；
