### ISSUE TITLE
关于双向复制粘贴得到的Y^out和Y^in

### ISSUE THREAD

**Issue by coisino** [DeepMed-Lab-ECNU/BCP#29]
img_a, img_b = volume_batch[:labeled_sub_bs], volume_batch[labeled_sub_bs:args.labeled_bs]
            uimg_a, uimg_b = volume_batch[args.labeled_bs:args.labeled_bs + unlabeled_sub_bs], volume_batch[args.labeled_bs + unlabeled_sub_bs:]
            ulab_a, ulab_b = label_batch[args.labeled_bs:args.labeled_bs + unlabeled_sub_bs], label_batch[args.labeled_bs + unlabeled_sub_bs:]
            lab_a, lab_b = label_batch[:labeled_sub_bs], label_batch[labeled_sub_bs:args.labeled_bs]
            with torch.no_grad():
                pre_a = ema_model(uimg_a)
                pre_b = ema_model(uimg_b)
                plab_a = get_ACDC_masks(pre_a, nms=1)
                plab_b = get_ACDC_masks(pre_b, nms=1)
                img_mask, loss_mask = generate_mask(img_a)
                unl_label = ulab_a * img_mask + lab_a * (1 - img_mask)
                l_label = lab_b * img_mask + ulab_b * (1 - img_mask)
关于这段代码，我有一个问题是：
在您的网络框架中所展示的是使用Labeled images的Ground Truth和使用Teacher模块对Unlabeled images生成的Pseudo label进行双向复制粘贴操作得到的Y^out和Y^in，但您在代码里用不是伪标签而是无标签图像的Ground Truth（ulab_a和ulab_b），这块我不是很明白。

**Comment by lxFang2022** [comment]
你好，我有同样的疑问，代码里用的是无标签图像的Ground Truth，而不是pretrined模型生成的伪标签。

**Comment by byhwhite** [comment]
ulab_a和ulab_b只是在399行以后的tensorboard记录中使用，为了看一下混合图片对应的真实标签长什么样子；在计算未标记图像区域损失函数的时候，监督信号用的是plab_a和plab_b



---原始邮件---
发件人: "Fang ***@***.***&gt;
发送时间: 2024年12月9日(周一) 上午9:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [DeepMed-Lab-ECNU/BCP] 关于双向复制粘贴得到的Y^out和Y^in (Issue #29)




 
你好，我有同样的疑问，代码里用的是无标签图像的Ground Truth，而不是pretrined模型生成的伪标签。
