### ISSUE TITLE
Why not cite and comapre with DACS and DSP?

### ISSUE THREAD

**Issue by sherlockholmesuk** [DeepMed-Lab-ECNU/BCP#3]
It is highly advisable to consider citing and comparing the approaches utilized in DACS and DSP when discussing your own method. 

It is imperative to delve into the **distinctions** between your proposed methodology and those put forth in DACS and DSP. All three approaches share the common principle of employing the **cut-and-paste idea**, with a focus on addressing the challenges of **semi-supervised learning**. It is worth noting that tackling the problem of unsupervised domain adaptation (UDA) presents an additional layer of complexity, as it involves bridging the domain gap between the source and target domains.

DACS: Domain Adaptation via Cross-domain Mixed Sampling, WACV 2021.
DSP: Dual Soft-Paste for Unsupervised Domain Adaptive Semantic Segmentation, MM 2021.

**Comment by byhwhite** [comment]
Thank you for bringing this to our attention! We apologize for not having previously reviewed the two papers you mentioned, as we were inundated with numerous papers. Following your suggestion, we have read these two papers and found their ideas to be closely aligned with those of our references [6] and [9]. Moving forward, we will be citing the papers you have mentioned in our future research. Once again, thank you for your valuable suggestion!

**Comment by byhwhite** [comment]
> It is highly advisable to consider citing and comparing the approaches utilized in DACS and DSP when discussing your own method.
> 
> It is imperative to delve into the **distinctions** between your proposed methodology and those put forth in DACS and DSP. All three approaches share the common principle of employing the **cut-and-paste idea**, with a focus on addressing the challenges of **semi-supervised learning**. It is worth noting that tackling the problem of unsupervised domain adaptation (UDA) presents an additional layer of complexity, as it involves bridging the domain gap between the source and target domains.
> 
> DACS: Domain Adaptation via Cross-domain Mixed Sampling, WACV 2021. DSP: Dual Soft-Paste for Unsupervised Domain Adaptive Semantic Segmentation, MM 2021.

Thank you for bringing this to our attention! We apologize for not having previously reviewed the two papers you mentioned, as we were inundated with numerous papers. Following your suggestion, we have read these two papers and found their ideas to be closely aligned with those of our references [6] and [9]. Moving forward, we will be citing the papers you have mentioned in our future research. Once again, thank you for your valuable suggestion!

**Comment by sherlockholmesuk** [comment]
Undoubtedly, the aforementioned papers, such as [9], espouse a shared concept of employing the "copy and paste" technique for data augmentation. These scholarly contributions were all published in the year 2021. In this epoch of copious publications, it is understandable that researchers may find themselves submerged in a deluge of numerous papers, particularly following a two-year interval. Nonetheless, it is incumbent upon the authors to address any raised concerns and explicate the nuances that differentiate these works.

Concretely, DACS put forth a unidirectional copy-and-paste strategy, specifically from labeled data to unlabeled data (Labeled -> Unlabeled). In contrast, DSP introduced a bidirectional copy-and-paste strategy that encompasses two discrete processes: copying from labeled to unlabeled data, and reciprocally, from unlabeled to labeled data (both Labeled -> Unlabeled and Unlabeled -> Labeled). DSP also incorporates two distinct strategies, namely hard paste and soft paste. To furnish a comprehensive evaluation of your method and to appropriately situate your paper within the existing literature, it is advisable to report the performance gain achieved in relation to the DACS baseline. Furthermore, it is imperative to elucidate the divergence between your approach and DSP, while also presenting the performance gains attained when employing the dual-hard paste strategy, particularly for the purposes of a thorough comparison.

**Comment by byhwhite** [comment]
> Undoubtedly, the aforementioned papers, such as [9], espouse a shared concept of employing the "copy and paste" technique for data augmentation. These scholarly contributions were all published in the year 2021. In this epoch of copious publications, it is understandable that researchers may find themselves submerged in a deluge of numerous papers, particularly following a two-year interval. Nonetheless, it is incumbent upon the authors to address any raised concerns and explicate the nuances that differentiate these works.
> 
> Concretely, DACS put forth a unidirectional copy-and-paste strategy, specifically from labeled data to unlabeled data (Labeled -> Unlabeled). In contrast, DSP introduced a bidirectional copy-and-paste strategy that encompasses two discrete processes: copying from labeled to unlabeled data, and reciprocally, from unlabeled to labeled data (both Labeled -> Unlabeled and Unlabeled -> Labeled). DSP also incorporates two distinct strategies, namely hard paste and soft paste. To furnish a comprehensive evaluation of your method and to appropriately situate your paper within the existing literature, it is advisable to report the performance gain achieved in relation to the DACS baseline. Furthermore, it is imperative to elucidate the divergence between your approach and DSP, while also presenting the performance gains attained when employing the dual-hard paste strategy, particularly for the purposes of a thorough comparison.

Thank you. We will consider your suggestion in our extension.
