### ISSUE TITLE
关于Unet和Vnet

### ISSUE THREAD

**Issue by Manty1998** [DeepMed-Lab-ECNU/BCP#30]
作者您好：
      我是刚接触图像分割的小白，十分感谢你们的代码和文章对我的学习起到了很大的作用！ 目前我尝试着对Unet结构进行改动，输出的结果有了一些变化；但我对Vnet进行改动时，涉及的参数比较多，代码很难调试，请问在这里，Vnet的作用是对图像进行切片吗？
      期待您的回复！

**Comment by byhwhite** [comment]
您好，感谢您对我们工作的关注。我们代码中的Unet是2D网络，意味着网络输入的图像是二维的；Vnet则是3D网络，他的输入是三维图像（MRI、CT这样的）。Unet和Vnet的作用都是对图像进行分割预测。
