### ISSUE TITLE
关于zero-centered mask

### ISSUE THREAD

**Issue by yinguanchun** [DeepMed-Lab-ECNU/BCP#31]
您好。看到您论文中提到三种masking strategy，并且最终采用的是zero-centered mask，其大小为βH × βW × βL，β=2/3，但我在修改代码的过程中发现，似乎生成的mask大小为βH × βW × L。
例如，假设图像的大小为3×3×3，则mask大小为2×2×2，实际测试生成的为2×2×3
![111](https://github.com/DeepMed-Lab-ECNU/BCP/assets/116438454/10ab78c2-7ae4-49ff-a219-628e379607a6)
![222](https://github.com/DeepMed-Lab-ECNU/BCP/assets/116438454/73cfe811-6280-4da4-a621-1361b50839e3)

**Comment by byhwhite** [comment]
您好，感谢您对我们工作的关注。我们文章中使用了三个公开数据集，ACDC数据集，LA数据集和NIH-Pancreas数据集，其中ACDC数据集是使用的2D网络以及2D图像输入，所以生成的mask也是2D的，您在这里调用的是ACDC数据集中使用的mask生成函数，所以你可以看到生成的mask是3*3的，这个mask*img操作会使得img中C维度中每一个H*W维度的二维图像与二维mask相乘，最终得到你图片中的结果。3D mask的生成函数可以在LA训练代码中找到。

**Comment by yinguanchun** [comment]
> 您好，感谢您对我们工作的关注。我们文章中使用了三个公开数据集，ACDC数据集，LA数据集和NIH-Pancreas数据集，其中ACDC数据集是使用的2D网络以及2D图像输入，所以生成的mask也是2D的，您在这里调用的是ACDC数据集中使用的mask生成函数，所以你可以看到生成的mask是3 X 3的，这个mask X img操作会使得img中C维度中每一个H*W维度的二维图像与二维mask相乘，最终得到你图片中的结果。3D mask的生成函数可以在LA训练代码中找到。
谢谢！
