### ISSUE TITLE
/data/byh_data/SSNet_data/ACDC

### ISSUE THREAD

**Issue by xinxin5555555** [DeepMed-Lab-ECNU/BCP#33]
您好，麻烦请问一下'/data/byh_data/SSNet_data/ACDC'这个路径是怎么获取的呀？运行该代码的时候找不到该文件夹，没有找到下载路径

**Comment by akakak47** [comment]
“/data/byh_data/SSNet_data/ACDC”这个应该是一个linux系统上的绝对路径，是作者在项目文件夹外创建的用于存放数据的文件夹，你可以自己建一个存放数据的文件，把数据放进去，然后将项目中的“/data/byh_data/SSNet_data/ACDC”修改为你的数据文件夹路径。
