### ISSUE TITLE
想问一下bcp项目的环境配置文件在哪？

### ISSUE THREAD

**Issue by andrew040105** [DeepMed-Lab-ECNU/BCP#34]
你好，想问一下bcp项目的环境配置文件在哪？没有找到requirement.txt文件，第一次尝试运行github项目的代码，不太清楚环境中要安装哪些包

**Comment by byhwhite** [comment]
您好，感谢您对我们工作的关注。我也是第一次公开代码，缺少相关经验，实在抱歉。您可以尝试运行，并根据报错来安装运行所需的库。
