### ISSUE TITLE
如何画不同方法的kernel dense estimations曲线？

### ISSUE THREAD

**Issue by wqhIris** [DeepMed-Lab-ECNU/BCP#35]
您好，感谢发布了优秀的工作。想请教如何画图5的kde分布曲线。
我自己理解的是seaborn.kdeplot似乎只能处理一维数据，如果选取输入图像，reshape(batchsize,-1)得到的也是二维数据，且第二维维数很大；如果选取模型中间层特征，除了上述问题，还有一个问题是：对于分割map来说，似乎无法按类标签分类特征。
请问您当时是如何确定kdeplot函数的输入变量的呢？

**Comment by byhwhite** [comment]
您好，感谢对我们工作的关注。VNet最后一个上采样层后是一个1*1的卷积层，这个卷积层以(B,filter_num,H,W,D)为输入，输出(B,C,H,W,D)的分割结果，我们使用(B,filter_num,H,W,D)这个特征与标签进行类别的对应。这一步可以看做是每个pixel拥有长度为filter_num的特征，每个pixel的类别与形状为(H,W,D)的真实标签也可以对应上。

**Comment by byhwhite** [comment]
你好，已更新`code/KDE_demo.py`。
