### ISSUE TITLE
结果图

### ISSUE THREAD

**Issue by CamillerFerros** [DeepMed-Lab-ECNU/BCP#36]
您好，我对您的工作很感兴趣，您的工作对我的启发非常大，这是一个优秀的工作！
可以请教一下您论文中的图4-LA数据集的分割结果图是用什么软件得到的吗，这是哪一个标签数据的结果图，我是初学者想通过可视化直观的看改进的效果，希望您能告诉我是用什么软件得到的可视化结果以及这是哪一个数据，十分期待您的回复！

**Comment by byhwhite** [comment]
您好，我们的结果图使用itk-snap软件对.nii.gz文件可视化。哪一个数据我们没有记录，抱歉。
