### ISSUE TITLE
Pancreas训练权重

### ISSUE THREAD

**Issue by Leesoon1984** [DeepMed-Lab-ECNU/BCP#38]
你好，请问能提供Pancreas数据集训练权重吗？

**Comment by byhwhite** [comment]
你好，已在README中更新此模型权重的百度云链接。

**Comment by CamillerFerros** [comment]
你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！

**Comment by CamillerFerros** [comment]
> 你好，已在README中更新此模型权重的百度云链接。


你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！

**Comment by byhwhite** [comment]
> > 你好，已在README中更新此模型权重的百度云链接。
> 
> 
> 你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！
> 
> 

你好，models文件夹下即为acdc和la数据集的训练模型

**Comment by CamillerFerros** [comment]
> > > 你好，已在README中更新此模型权重的百度云链接。
> > 
> > 
> > 你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！
> 
> 你好，models文件夹下即为acdc和la数据集的训练模型

可以再请教一下蓝色的圆圈是怎么画的吗，对这方面不是很了解，谢谢

**Comment by CamillerFerros** [comment]
> > > 你好，已在README中更新此模型权重的百度云链接。
> > 
> > 
> > 你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！
> 
> 你好，models文件夹下即为acdc和la数据集的训练模型

，您好，可以再请教一下蓝色的圆圈是怎么画的吗，对这方面不是很了解，谢谢

**Comment by byhwhite** [comment]
> > > > 你好，已在README中更新此模型权重的百度云链接。
> > > 
> > > 
> > > 你好，可以提供一下ACDC数据集和LA数据集的训练权重吗，非常感谢！
> > 
> > 你好，models文件夹下即为acdc和la数据集的训练模型
> 
> ，您好，可以再请教一下蓝色的圆圈是怎么画的吗，对这方面不是很了解，谢谢

ppt

**Comment by geek-APTX4869** [comment]
表2V-Net的结果是怎样得到的呢，想学习一下
