### ISSUE TITLE
 About copy and paste

### ISSUE THREAD

**Issue by Manty1998** [DeepMed-Lab-ECNU/BCP#39]
Hello author, thank you for your work’s contribution to my study. I still have some questions at the moment. 1. When the foreground image is cropped, will it be cropped to the heart area? 2. If you crop to the heart area and paste it randomly, will two target areas be formed in the pasted image? 3. Regarding the foreground image, is it randomly pasted on any position of the background image?
Looking forward to your answer!

**Comment by byhwhite** [comment]
> Hello author, thank you for your work’s contribution to my study. I still have some questions at the moment. 1. When the foreground image is cropped, will it be cropped to the heart area? 2. If you crop to the heart area and paste it randomly, will two target areas be formed in the pasted image? 3. Regarding the foreground image, is it randomly pasted on any position of the background image?
> Looking forward to your answer!

Hi, the foreground image crop is randomly cropped from image and pasted on background image.

**Comment by lpc-97** [comment]
Traceback (most recent call last):
  File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 481, in <module>
    self_train(args, pre_snapshot_path, self_snapshot_path)
  File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 378, in self_train
    net_input_unl = uimg_a * img_mask + img_a * (1 - img_mask)
RuntimeError: The size of tensor a (18) must match the size of tensor b (6) at non-singleton dimension

**Comment by Manty1998** [comment]
Hello author, thank you for your reply! But my question is: 1. If the foreground image is cropped randomly, how can we make sure that the cropped foreground will definitely contain the segmentation target we need?

**Comment by byhwhite** [comment]
> Hello author, thank you for your reply! But my question is: 1. If the foreground image is cropped randomly, how can we make sure that the cropped foreground will definitely contain the segmentation target we need?

First, the image of the dataset is almost ROI. Second, the mask used in BCP is (2/3*img_length, 2/3*img_width), which could promise region of interest is in foreground.

**Comment by Manty1998** [comment]
这是来自陆满替邮箱自动回复邮件。您好：     您的邮件本人已收悉，会在方便时间第一查看处理。

**Comment by Manty1998** [comment]
I got it! Thank you for your reply.
