### ISSUE TITLE
questions about the data distribution

### ISSUE THREAD

**Issue by Kedaya66** [DeepMed-Lab-ECNU/BCP#4]
hello! I have a question about the kernel dense eastimation part
What methods was used in drawing image distribution of labeled data and unlabeled data?

**Comment by Kedaya66** [comment]
How can I analyses my own medical image dataset distribution

**Comment by byhwhite** [comment]
> hello! I have a question about the kernel dense eastimation part What methods was used in drawing image distribution of labeled data and unlabeled data?

Hi! We use `seaborn.kdeplot` to plot the figure. For analysis, you can select pixels (or network's feature) of labeled data and unlabeled data belong to the same class and then draw them.
