### ISSUE TITLE
Traceback (most recent call last):   File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 481, in <module>     self_train(args, pre_snapshot_path, self_snapshot_path)   File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 378, in self_train     net_input_unl = uimg_a * img_mask + img_a * (1 - img_mask) RuntimeError: The size of tensor a (18) must match the size of tensor b (6) at non-singleton dimension 

### ISSUE THREAD

**Issue by lpc-97** [DeepMed-Lab-ECNU/BCP#40]
Traceback (most recent call last):
  File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 481, in <module>
    self_train(args, pre_snapshot_path, self_snapshot_path)
  File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 378, in self_train
    net_input_unl = uimg_a * img_mask + img_a * (1 - img_mask)
RuntimeError: The size of tensor a (18) must match the size of tensor b (6) at non-singleton dimension 

————

please help me

**Comment by byhwhite** [comment]
> Traceback (most recent call last): File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 481, in self_train(args, pre_snapshot_path, self_snapshot_path) File "/home/test/03.BCP-main/./code/ACDC_BCP_train.py", line 378, in self_train net_input_unl = uimg_a * img_mask + img_a * (1 - img_mask) RuntimeError: The size of tensor a (18) must match the size of tensor b (6) at non-singleton dimension
> 
> ————
> 
> please help me

Have you changed the args.labeled_bs to 6? args.labeled_bs should be half of args.batch_size, think about set args.labeled_bs as 12.

**Comment by lpc-97** [comment]
--root_path："/home/test/02.UGPCL/ACDC/ will error

but "/home/test/02.UGPCL/ACDC 

is right 
intersting
