### ISSUE TITLE
what's the difference between your method and classmix

### ISSUE THREAD

**Issue by haomingziranggeizhu** [DeepMed-Lab-ECNU/BCP#7]
Hello, I have read your paper, but I have a question of your paper.
My question is what's the difference between your method and classmix?
why not compare with classmix?

**Comment by byhwhite** [comment]
> Hello, I have read your paper, but I have a question of your paper. My question is what's the difference between your method and classmix? why not compare with classmix?

Hi! Thanks for your good questions. The difference is that our method aims to alleviate the empirical distribution mismatch problem in semi-supervised learning by using labeled and unlabeled data symmetrically. In contrast, Classmix utilizes only labeled data through supervised loss and classmix within unlabeled data. There are too many methods exploring the potential of copy-paste, making it difficult and unrealistic for us to compare all of them.
