### ISSUE TITLE
A question about only supervisied.

### ISSUE THREAD

**Issue by zhibotian** [DeepMed-Lab-ECNU/BCP#8]
Hello, thank you very much for your excellent work. I have found that when using labeled images (including 4 labeled and 0 unlabeled images) to train the network, the training results are very poor compared to Table 1 in the paper. Could you provide me with more detailed information related to the training? This information would be very helpful for me.

**Comment by byhwhite** [comment]
> Hello, thank you very much for your excellent work. I have found that when using labeled images (including 4 labeled and 0 unlabeled images) to train the network, the training results are very poor compared to Table 1 in the paper. Could you provide me with more detailed information related to the training? This information would be very helpful for me.

Hi! Since we strictly follow the setting of SS-Net, the results reported in Table 1 are same as SS-Net. We got comparable result of only 5% labeled (4 labeled and 0 unlabeled) training. I would like to get more details about the problem you mentioned.
