### ISSUE TITLE
 5% labeled data

### ISSUE THREAD

**Issue by xiaoxiaoma111** [DeepMed-Lab-ECNU/BCP#9]
How can I achieve a 5% labeled data and how should I modify it？I don't understand the code, I hope you can answer it，thanks

**Comment by byhwhite** [comment]
> How can I achieve a 5% labeled data and how should I modify it？I don't understand the code, I hope you can answer it，thanks

Hi! You can modify the labeled ratio of training by changing args.labelnum in the parameters spacing. Please note that args.labelnum represents the number of labeled samples, not the ratio. For ACDC, args.labelnum should be set to 3 to train with 5% labeled data and 7 to train with 10%. For LA, set it to 4 to train with 5% and 8 to train with 10%.

**Comment by Manty1998** [comment]
Hello, author, I am a beginner. In the Vnet row in Table 1, how do I modify the code and set the proportion of unlable to 0? Looking forward to your reply!

**Comment by byhwhite** [comment]
您好，最近比较忙，没来得及检查邮件，抱歉。问题已解决了吗？

**Comment by Manty1998** [comment]
这是来自陆满替邮箱自动回复邮件。您好：     您的邮件本人已收悉，会在方便时间第一查看处理。
